### ISSUE TITLE
Got error adding crescensdo with factory presets from Stevie

### ISSUE THREAD

**Issue by tompad2** [jeremybernstein/ReaScripts#1]
Message:

ImGui assertion failed.

`(g.CurrentWindowStack.Size == 1) && "Mismatched Begin/BeginChild vs End/EndChild calls: did you forget to call End/EndChild?"`

And here is the output from console:
`...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:2862: attempt to perform arithmetic on a nil value
stack traceback:
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:3555: in metamethod 'div'
	...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:2862: in function 'DoProcessParams'
	...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:2902: in function 'ProcessParams'
	...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:4726: in function 'GetRowTextAndParameterValues'
	...y72 Scripts\MIDI Editor\Transformer/TransformerExtra.lua:265: in field 'formatter'
	...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:3704: in function 'TransformerLib.actionRowToNotation'
	...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:3736: in function 'ActionRowsToNotation'
	...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:4541: in function 'GetCurrentPresetState'
	...key72 Scripts\MIDI Editor\Transformer/TransformerLib.lua:4766: in function 'TransformerLib.update'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:209: in upvalue 'doUpdate'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:225: in upvalue 'doActionUpdate'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:688: in upvalue 'endPresetLoad'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:1264: in upvalue 'generatePresetMenu'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:1241: in upvalue 'generatePresetMenu'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:1241: in upvalue 'generatePresetMenu'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:1241: in upvalue 'generatePresetMenu'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:1241: in local 'generatePresetMenu'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:3512: in upvalue 'windowFn'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:3730: in function <...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:3695>
	[C]: in function 'xpcall'
	...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:3762: in function <...onkey72 Scripts\MIDI Editor\sockmonkey72_Transformer.lua:3762>
`

Is this something I made wrong?
Or is it an error in preset?

**Comment by jeremybernstein** [comment]
Thanks, this should be fixed with v1.0.10

**Comment by tompad2** [comment]
...forgot to tell you - I think this tool is amazing!
Thanks for your great work.
Merry christmas!
